greendiary/account/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
    path('signup/', views.signup, name="signup"),
]

greendiary/diary/urls.py
from django.urls import path
from .views import DiaryCreate, DiaryList, CalendarView, DiaryDetail, DiaryDelete, DiaryEdit
from django.conf.urls.static import static
from django.conf import settings
from . import views

app_name = 'diary'

urlpatterns = [
    path("", views.home, name="home"),
    path("create/", DiaryCreate.as_view(), name="create"),
    path("calendar/", CalendarView.as_view(), name="calendar"),
    path("list/", DiaryList.as_view(), name="list"),
    path("detail/<int:pk>", DiaryDetail.as_view(), name="detail"),
    path("delete/<int:pk>", DiaryDelete.as_view(), name="delete"),
    path("edit/<int:pk>", DiaryEdit.as_view(), name="edit"),
    path("news/", views.news, name="news"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greendiary/greendiary/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')),
    path('account/', include('account.urls')),
]

greendiary/account/models.py
from django.db import models
from django.conf import settings
# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    nickname = models.CharField(max_length=11, blank=True)
    points = models.IntegerField(default=0)

    #포인트를 올리는 함수.
    def get_points(self, points):
        self.points += points
        self.save()

greendiary/diary/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import User

# Create your models here.
class Diary(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user")
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to = 'photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__ (self):
        return "text: " + self.text

greendiary/account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib import auth
from .models import Profile


# Create your views here.
def signup(request):
    if request.user.is_authenticated:
        return redirect("diary:home")

    if request.method == "POST":
        signup_form = UserCreationForm(request.POST)
        if signup_form.is_valid():
            user = signup_form.save()
            Profile.objects.create(user=user)
            auth.login(request, user)
            return redirect("diary:home")
        
    else :
        signup_form = UserCreationForm()

    return render(request, 'account/signup.html', {'signup_form':signup_form})

def login(request):
    if request.user.is_authenticated:
        return redirect("diary:home")

    if request.method == "POST":
        login_form = AuthenticationForm(request, request.POST)
        if login_form.is_valid():
            auth.login(request, login_form.get_user())
        return redirect("diary:home")
        
    else:
        login_form = AuthenticationForm()
        
    return render(request, 'account/login.html', {'login_form':login_form})

def logout(request):
    auth.logout(request)
    return redirect("diary:home")

greendiary/diary/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404, HttpResponse
from django.http import HttpResponse, HttpResponseRedirect 

from .models import Diary
from account.models import Profile

from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse

from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.utils import timezone

from datetime import datetime, timedelta, date
from django.utils.safestring import mark_safe
from .calendar import Calendar
import calendar

# Create your views here.
def home(request):
    return render(request, 'home.html')

def news(request):
    return render(request, 'diary_news.html')

class CalendarView(ListView):
    model = Diary
    template_name_suffix = '_calendar'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        cal = Calendar(d.year, d.month)
        html_cal = cal.formatmonth(withyear=True)
        context['calendar'] = mark_safe(html_cal)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_day):
    if req_day:
        year, month = (int(x) for x in req_day.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(day):
    first = day.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(day):
    days_in_month = calendar.monthrange(day.year, day.month)[1]
    last = day.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month

class DiaryList(ListView):
    model = Diary
    template_name_suffix = '_list'

class DiaryCreate(CreateView):
    model = Diary
    template_name_suffix = '_create'
    fields = '__all__'
    success_url = '/'

    def form_valid(self, form):
        form.instance.author_id = self.request.user.id
        if form.is_valid():
            form.instance.save()
            self.request.user.profile.get_points(1)
            return redirect('/')
        else:
            return self.render_to_response({'form':form})


class DiaryDelete(DeleteView):
    model = Diary
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한 없음')
            return HttpResponseRedirect('/')
        else:
            return super(DiaryDelete, self).dispatch(request, *args, **kwargs)


class DiaryDetail(DetailView):
    model = Diary
    template_name_suffix = '_detail'

class DiaryEdit(UpdateView):
    model = Diary
    template_name_suffix = '_edit'
    fields = ['text', 'image']
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할권한없음')
            return HttpResponseRedirect('/')
        else:
            return super(DiaryEdit, self).dispatch(request, *args, **kwargs)

def news(request):
    return render(request, 'diary/diary_news.html')

greendiary/templates/base.html
{% load static %}
    <head>
        <!--style.css file 가져오기-->
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
        <link rel="stylesheet" href="{% static 'css/calendar.css' %}">
        <link href="https://fonts.googleapis.com/css2?family=Poor+Story&display=swap" rel="stylesheet">
        <link
    rel="stylesheet"
    href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css"
  />
        <!--bootstrap 호출
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
        -->
        
	    <title>초록일기</title>
    </head>
    <style>
     .site{
       width: 1250px;
       
       margin: 0 auto;
       
     }

    </style>
     
    <body>
    <div class="site">
      
      <div class="grid">
        
        
          
          <div class="header-gd">
            
            <h1><a href="{% url 'diary:home' %}">&nbsp;
              <img src="{% static 'images/leaf.png' %}">
              
              초록일기&nbsp;</a></h1>
             
          
        </div>
         

        <div class="header">
          <div class="vercenter">
            <div class="right">
              {% if user.is_authenticated %}
              <a href="{% url 'logout' %}">({{ user.username }})&nbsp;&nbsp;&nbsp;&nbsp;<i class="fas fa-sign-out-alt"></i>&nbsp;로그아웃&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
              {% else %}
              
              <a href="{% url 'login' %}"><i class="fas fa-sign-in-alt"></i>&nbsp;로그인&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
              <a href="{% url 'signup' %}"><i class="fas fa-user-plus"></i>&nbsp;회원가입&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
              {% endif %}
        </div>
        </div>
        </div>
      
        
          <div class="sidebar">
           <div id="container">
             
            <ul>
            <br></br>
            <li><a href="{% url 'diary:news' %}"><img src="{% static 'images/newspaper.png' %}">&nbsp;&nbsp;환경뉴스</a></li>
            <li><a href="{% url 'diary:calendar'%}"><img src="{% static 'images/diary.png' %}">&nbsp;&nbsp;다이어리</a>
              <ul>
                <li><a href="{% url 'diary:calendar'%}">- 나의 다이어리</a></li>
                <li><a href="{% url 'diary:list' %}">- 다이어리 리스트</a></li>
                
              </ul>
            </li>
            <li><a href=""><img src="{% static 'images/farming.png' %}">&nbsp;&nbsp;정원</a>
              <ul>
                <li><a href="">- 나의 정원</a></li>                
              </ul>
            </li>
              
             
           </ul>
           
          </div>
          </div>
    {% block content %}
    {% endblock %}
      </div>
    </div>
    </body>
    

greendiary/templates/diary/diary_calendar.html
{% extends 'base.html' %}


<body>
    
    <div class="grid">
        {% block content %}
        
        <div class="content">
            
        <h1 style="color: black;">나의 다이어리</h1>
        
            
        
        {{calendar}}
        
    </div>
    <div class="right">
    <a href="{% url 'diary:calendar' %}?{{ prev_month }}" title="이전 달">
        <i class="fas fa-angle-left fa-2x"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
    
    <a href="{% url 'diary:calendar' %}?{{ next_month }}">
        <i class="fas fa-angle-right fa-2x"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
        
            <a href="{% url 'diary:create' %}">
            <i class="fas fa-pencil-alt fa-2x"></i>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</a>
    </div>
    
    {% endblock %}
    
</div>
</body>

greendiary/templates/diary/diary_create.html
{% extends 'base.html' %}

<div class="grid">
    {% block content %}
        <div class="content">
            <h1>일기작성</h1>
    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Upload">
    </form>
        </div>
    {% endblock %}
</div>

greendiary/templates/diary/diary_delete.html
{% extends 'base.html' %}
{% block content %}
<h1>삭제 페이지</h1>
  <div class="alert alert-secondary" role="alert" >
    <img src="{{ object.image.url }}">
    <p>{{object}}을(를) 지우시겠습니까?</p>
  </div>
  
  <form action="" method = "post">
      {%csrf_token %}
      <input type= "submit" value = "Ok">
  </form>
{% endblock %}

greendiary/templates/diary/diary_detail.html
{% extends "base.html" %}

<div class="grid">
    {% block content %}
        <div class="content">
          <div class="row">
    <div class="col-md-12">
        <div class="row">
            <img src="{{ object.image.url }}">
			      <p>{{ object.created }}</p>
            <p>{{ object.text }}</p>
            {% if object.author == request.user %}
                <p><a href="{% url 'diary:edit' object.id %}">[수정]</a>
                   <a href="{% url 'diary:delete' object.id %}">[삭제]</a></p>
            {% endif %}
        </div>
    </div>
  </div>
        </div>
    {% endblock %}
</div>

greendiary/templates/diary/diary_edit.html
{% extends 'base.html' %}
<<<<<<< HEAD
{% block content %}
<div class="container">
    <h1>수정 페이지</h1>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.as_p}}
        <br>
        <input type="submit" value="Upload">        <!--글 수정 가능 & 사진 다른 걸로 교체 가능 & 다시 올렸을 때 날짜 안바뀜-->
    </form>
</div>

{% endblock %}
=======
<div class="grid">
    {% block content %}
        <div class="content">
	
        </div>
    {% endblock %}
</div>
>>>>>>> c3f71a7855dd3e1725dacc604c24c0623ca5976a

greendiary/templates/diary/diary_list.html
{% extends 'base.html' %}

<div class="grid">
        {% block content %}
        <div class="content">
	<h1>일기 리스트</h1>
	{% for object in object_list %}
	{% if object.author == request.user %}
			<img src="{{ object.image.url }}">
			<p>{{ object.created }}</p>
			<p>{{ object.text }}
			<a href="{% url 'diary:detail' object.id %}">[더보기]</a></p>
	{% endif %}
	{% endfor %}
</div>
{% endblock %}
</div>

greendiary/templates/diary/diary_news.html
{% extends 'base.html' %}

<body>
    <div class="grid">
      {% block content %}
        <div class="content">

          <h1> 이곳에 넣으시면 돼요!</h1>
          <!-- 위쪽에 div - grid, content 있는데 저 2개 div 안으로 내용이 들어가야 해요 
                즉, 이곳에 내용 넣으시면 됩니다! -->

        </div>
      {% endblock %}
    </div>
</body>

greendiary/templates/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<html>

    <head>       
    </head>
    <body>
        
        <h1>안녕하세요. 초록일기입니다.</h1>
    </body>
</html>

{% endblock %}